name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby 3.3.4
    steps:
      - uses: actions/checkout@v4

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: zlib1g-dev libbz2-dev build-essential libstdc++-12-dev
          version: 1.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Install dependencies
        run: bundle exec rake install_deps

      - name: Compile ext
        run: bundle exec rake compile

      - name: RSpec
        run: bundle exec rspec

      - name: Rubocop
        run: bundle exec rubocop --parallel